name: Main workflow

on:
  - push
  - pull_request

jobs:
  create_draft_release:
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_draft_release.outputs.upload_url }}

    steps:
      - name: Create draft release on tags
        id: create_draft_release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  build:
    needs: create_draft_release

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-18.04
          - windows-latest
        ocaml-version:
          - 4.11.1
        skip_test:
          - false
        include:
          - os: macos-latest
            suffix: x86_64-apple-darwin
          - os: ubuntu-18.04
            ocaml-version: 4.11.1
            suffix: x86_64-unknown-linux-gnu
          - os: ubuntu-20.04
            ocaml-version: 4.11.1+musl+static+flambda
            suffix: x86_64-unknown-linux-musl
          - os: windows-latest
            suffix: x86_64-pc-windows-gnu
            stdlib_path: D:\a\caramel\caramel\_build\default\src\stdlib

    env:
      SKIP_TEST: ${{ matrix.skip_test }}
      OCAML_VERSION: ${{ matrix.ocaml-version }}
      OS: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cached Infra
        uses: actions/cache@v2
        env:
          cache-name: cached-opam
        with:
          path: |
           ~/.opam
           _build
           C:\cygwin
           D:\a\caramel\caramel
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}-${{ env.cache-name }}-${{ hashFiles('**/*.opam*') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.ocaml-version }}-${{ env.cache-name }}-
            ${{ matrix.os }}-${{ matrix.ocaml-version }}-
            ${{ matrix.os }}-
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Set git user
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions-bot@users.noreply.github.com
      
      - name: Define env (unix)
        if: ${{ runner.os != 'Windows' }}
        run: echo "::set-env name=GITHUB_TAG::${GITHUB_REF#refs/*/}"
      
      - name: Define env (macos)
        if: ${{ runner.os == 'macOS' }}
        run: echo "::set-env name=PKG_CONFIG_PATH::$(brew --prefix openssl)/lib/pkgconfig"

      - name: Define env (windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          $tag = "${{github.ref}}".Split("/")["${{github.ref}}".Split("/").Length -1]
          echo "::set-env name=GITHUB_TAG::$(echo $tag)"
          echo "::set-env name=CARAMELC_STDLIB_PATH::${{ matrix.stdlib_path }}"
      
      - name: Install dependencies
        run: |
          opam depext .
          opam install --deps-only .
          opam install ocamlformat

      - name: Build project
        run: opam exec -- dune build -p doi2bib

      - name: Check code formatting
        if: ${{ success() && startsWith(runner.os, 'Linux') }}
        run: opam exec -- dune build @fmt

      - name: Create release archive
        if: ${{ success() }}
        run: |
          opam exec -- tar czf release.tar.gz -C _build/default/bin/ doi2bib.exe
      - name: Upload build artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          path: release.tar.gz
          name: caramel-${{ env.GITHUB_TAG }}-${{ matrix.suffix }}.tar.gz
          if-no-files-found: error

      - name: Upload release tarball
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft_release.outputs.upload_url }}
          asset_path: release.tar.gz
          asset_name: caramel-${{ env.GITHUB_TAG }}-${{ matrix.suffix }}.tar.gz
          asset_content_type: application/zip